Repository capstone-coal/pycoal, pull requests merged in 2018-05, with the labels that each got.

#147 Fix pycoal path of the docker image at README.str
  README.rst
Labels: Docker, documentation

#150 ISSUE-149 More flexible detection of gdal_proximity.py in Mac OSX 'Darwin' target environment
  pycoal/environment.py
  pycoal/tests/environment_test.py
  pycoal/tests/test.py
Labels: enhancement, environment

#152 USGS Spectral Library 7 documentation
  examples/README.rst
Labels: documentation, enhancement
