Repository capstone-coal/pycoal, pull requests merged in 2019-10, with the labels that each got.

#174 ISSUE-173 Readthedocs.io build failing
  .readthedocs.yml
Labels: build, documentation, enhancement

#171 Issue 165
  examples/constants.py
  examples/example07_mineral.py
  examples/example_environment.py
  examples/example_mineral.py
  examples/example_mineral_lstm.py
  examples/example_mining.py
  examples/example_sam.py
  examples/example_spectra.py
  examples/example_spectral07.py
  examples/example_splib06.py
  pycoal/mineral.py
Labels: enhancement, examples

#178 Issue 161
  examples/constants.py
  examples/example_environment.py
  examples/example_mineral.py
  examples/example_mineral_lstm.py
  examples/example_mining.py
  examples/example_sam.py
  examples/example_spectra.py
  examples/example_spectral07.py
  examples/example_splib06.py
  pycoal/cli/environment.py
  pycoal/cli/mineral.py
  pycoal/cli/mining.py
  pycoal/conversion.py
  pycoal/environment.py
  pycoal/mineral.py
  pycoal/mining.py
  pycoal/tests/environment_test.py
  pycoal/tests/mineral_test.py
  pycoal/tests/mining_test.py
  pycoal/tests/test.py
  setup.py
Labels: enhancement
